#!/usr/bin/env python

import os
import sys
import shutil
import subprocess
import tempfile
import json

def main(argv):
    tarball = argv[1]
    tag = argv[2]
    (name,version) = tag.rsplit(':', 1)

    tmpdir = tempfile.mkdtemp('tmp-fdii')
    subprocess.check_call(['tar', 'xf', os.path.abspath(tarball)], cwd=tmpdir)
    repospath = tmpdir + '/repositories'
    with open(repospath) as f:
        reposinfo = json.load(f)
    reposinfo_new = {}
    for k,v in reposinfo.iteritems():
        if not k.startswith('Fedora'):
            reposinfo_new[k] = v
            continue
        subkeys = v.keys() 
        assert len(subkeys) == 1
        uuid = v[subkeys[0]]
        reposinfo_new[name] = {}
        reposinfo_new[name][version] = uuid
    with open(repospath, 'w') as f:
        json.dump(reposinfo_new, f)

    try:
        tarout = subprocess.Popen(['tar', 'cf', '-', '.'], cwd=tmpdir,
                                  stdout=subprocess.PIPE)
        subprocess.check_call(['docker', 'load'], stdin=tarout.stdout)
    finally:
        shutil.rmtree(tmpdir)

if __name__ == '__main__':
    main(sys.argv)
    

